---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - BlogPostExtension
VersionTruncator:
  version_limit: 1
  draft_limit: 1
  delete_old_page_types: false
  vacuum_tables: false
SilverStripe\View\SSViewer:
  themes:
    - $public
    - scope
    - $default
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    file:
      public: '0644'
      private: '0600'
